### ISSUE TITLE
Need new icons for iCloud and iCloud Calendar

### ISSUE THREAD

**Issue by aashishpsaini** [bigbinary/neeto-icons#294]
Sample images:

https://www.icloud.com :
<img width="107" alt="image" src="https://github.com/user-attachments/assets/f9557a3c-b47a-47f6-aab6-0963f3ff5058">

https://www.icloud.com/calendar/
<img width="376" alt="image" src="https://github.com/user-attachments/assets/de4c4fdb-f638-4086-84bb-33f0e49a9a2f">

In case of calendar, logo shows current day and date

**Comment by subins2000** [comment]
@aashishpsaini _a Please provide more context on the usage of this icon

**Comment by aashishpsaini** [comment]
Currently on Settings page,

<img width="1413" alt="image" src="https://github.com/user-attachments/assets/b84a18d4-bb4f-4583-8ffe-1e0aca4560b7">

Then on the integration page,

<img width="1386" alt="image" src="https://github.com/user-attachments/assets/fa7520cd-89cc-4a09-bd44-14efa9935f40">

and connect page

<img width="1422" alt="image" src="https://github.com/user-attachments/assets/69152fff-8193-4155-85bc-5ad299fbb9d3">


We are showing Apple logo, It would be better if we show the icloud logo and icloud calendar logo according to page respectively,
<img width="99" alt="image" src="https://github.com/user-attachments/assets/bfc49143-1eae-496a-b15d-713c8125cee2">


<img width="192" alt="image" src="https://github.com/user-attachments/assets/bb74bba5-4eac-4e61-adfa-5a4e9d3f64bf">



Again this is my thought, final decision is on the product people.
CC: @Tsudhishnair

**Comment by subins2000** [comment]
@AbhayVAshokan _a I think the Apple logo is fine enough. We are mentioning "iCloud" next to it. So it's alright
