### ISSUE TITLE
Generic icons for OS and browser

### ISSUE THREAD

**Issue by anil-anand** [bigbinary/neeto-icons#297]
Something like this for OS:
- https://www.vecteezy.com/vector-art/4748381-abstract-operating-system-icon-illustration

Something like this for browser:
- https://www.vectorstock.com/royalty-free-vector/sphere-planet-browser-icon-vector-23896088
- https://www.flaticon.com/free-icon/browser_3771343

@avinashanilkumar _a
Could you please have a look?

**Comment by praveen-murali-ind** [comment]
@thomas-mathai _a Please add the icons.
