### ISSUE TITLE
Create typeface logo for NeetoEngage

### ISSUE THREAD

**Issue by josephmathew900** [bigbinary/neeto-icons#312]
Use the same logo of NeetoChangelog for NeetoEngage.

@avinashanilkumar _a

**Comment by avinashanilkumar** [comment]
@josephmathew900 _a Please find the logo: https://www.figma.com/design/Dpwu6N0rAvhAF23veWpGYR/Brand-Design-V3?node-id=2369-55&t=YrTCvu3pYW9hkK6G-4
