### ISSUE TITLE
Create icons

### ISSUE THREAD

**Issue by farhanlatheef** [bigbinary/neeto-icons#323]
https://www.figma.com/design/zmzMnLmUzTBdP0koSzFeWV/neetoRecord?node-id=1425-1560&node-type=frame&t=Jm0idLTTMrgRGFIh-0

Camera resize
About 
General
Clear cache

**Comment by farhanlatheef** [comment]
@avinashanilkumar _a

**Comment by avinashanilkumar** [comment]
@farhanlatheef Please find the icons: https://www.figma.com/design/t2CLe7RVJYwUq9E8Or1mQA/01-Fundamentals?node-id=103-674&t=4FzfZmE1NowufJKl-4
