### ISSUE TITLE
Enhance Home Icon to Better Represent a "Home"

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-icons#327]
The current home icon can be improved to feel more like a "home".

Ref - https://github.com/bigbinary/neeto-engineering-ui-ux/issues/357

@avinashanilkumar _a

**Comment by avinashanilkumar** [comment]
@praveen-murali-ind please find the new home icon: https://www.figma.com/design/t2CLe7RVJYwUq9E8Or1mQA/01-Fundamentals?node-id=7154-34&t=HmHF2u2TuyHi5ozl-4 

cc: @KirtiGulati

**Comment by praveen-murali-ind** [comment]
@thomas-mathai _a Please update the "Home" icon.
