### ISSUE TITLE
Add Card brand icons

### ISSUE THREAD

**Issue by rishadp2747** [bigbinary/neeto-icons#329]
Part of https://github.com/bigbinary/neeto-engineering-web/issues/985

Ref: https://support.stripe.com/questions/where-to-find-logos-for-accepted-credit-card-types

[Mastercard](https://brand.mastercard.com/brandcenter/mastercard-brand-mark/downloads.html), [Discover](http://www.discoversignage.com/), [American Express](https://www.americanexpress.com/content/dam/amex/us/merchant/pdf/gms-stripe-pop-coverage.pdf), [JCB](https://www.jcb.co.jp/bdmanual/en/basicDesignElements/jcbEmblem/index01download01.html), [China UnionPay](https://www.unionpayintl.com/en/mediaCenter/brandCenter/artworkDownloadCenter/identification.shtml), and [Visa](https://www.merchantsignage.visa.com/brand_guidelines)

**Comment by rishadp2747** [comment]
@thomas-mathai _a

**Comment by thomas-mathai** [comment]
@avinashanilkumar _a Can you please create the card brand icons?

**Comment by avinashanilkumar** [comment]
@thomas-mathai _a please find the icons: https://www.figma.com/design/t2CLe7RVJYwUq9E8Or1mQA/01-Fundamentals?node-id=7188-54&t=sVvPWlD87ITe5LqD-4 

cc: @rishadp2747
