### ISSUE TITLE
Add icon for color picker

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-icons#331]
Part of https://github.com/bigbinary/neeto-ui/issues/2374

[Figma](https://www.figma.com/design/YxylhnvBCVt1PrhWV3WIQb/neetoCal?node-id=6423-22574&t=UJ5Rmt5BCwpeyHDf-1)

@praveen-murali-ind _a

**Comment by praveen-murali-ind** [comment]
@avinashanilkumar _a Could you please add an icon for the color picker?

Ref
<img width="93" alt="Screenshot 2024-11-27 at 10 50 11 AM" src="https://github.com/user-attachments/assets/329fff4d-3c61-4c04-b58a-71b93c79f5cd">

**Comment by avinashanilkumar** [comment]
@praveen-murali-ind Please find the icon: https://www.figma.com/design/t2CLe7RVJYwUq9E8Or1mQA/01-Fundamentals?node-id=7213-54&t=jtBpOVIhm8WJDLSm-4
